name = "xcp" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern=
"cf.shopee.sg.xcp.trudjan.my.id"
custom-domain=true
[[routes]]
pattern=
"cf.shopee.sg.xcp.trudjan.my.id"
custom-domain=true
[[routes]]
pattern=
"cf.shopee.sg.xcp.trudjan.my.id"
custom-domain=true
[[routes]]
pattern=
"cf.shopee.sg.xcp.trudjan.my.id"
custom-domain=true

[vars]
UUID = "5bcaa1ac-83c2-4a26-8f38-88763e963a73"
# PROXYIP = "35.219.50.99"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
# UUID = "5bcaa1ac-83c2-4a26-8f38-88763e963a73"
